### ISSUE TITLE
[bug] should require broccoli@3, if not should show an error page?

### ISSUE THREAD

**Issue by grconrad** [gabrielcsapo/broccoli-inspector#23]
Tried broccoli-inspector 0.2.1 in a project using broccoli 2.3.0 and the `ember serve` errored out:

```
  - stack: TypeError: Cannot read property 'entries' of undefined
    at nodeWrappersById (/my/project/node_modules/broccoli-inspector/lib/middleware.js:92:23)
    at module.exports (/my/project/node_modules/broccoli-inspector/lib/middleware.js:15:34)
    at module.exports (/my/project/server/index.js:25:47)
```

**Comment by gabrielcsapo** [comment]
Agreed, we should have a check in the middleware when building the application to show an unsupported page. Might likely be a semver range something like `broccoli > 3`?
